<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$category = $objectManager->get('Magento\Framework\Registry')->registry('current_category');//get current category
$subcats = $category->getChildrenCategories();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
?>
<ul class="sub-cat">
    <?php
    foreach ($subcats as $subcat) {
            $_category = $objectManager->create('Magento\Catalog\Model\Category')->load($subcat->getId());
            $_outputhelper = $this->helper('Magento\Catalog\Helper\Output');
            $subcaturl = $subcat->getUrl();            
            $_imgHtml = '';
            if ($_imgUrl = $_category->getImageUrl()) {
                $_imgHtml = '<img src="' . $_imgUrl . '" />';
                $_imgHtml = $_outputhelper->categoryAttribute($_category, $_imgHtml, 'image');
                /* @escapeNotVerified */
                //echo '<li><a href="' . $subcaturl . '" title="' . $subcat->getName() . '">' . $_imgHtml . '</a></li>';
            } ?>
            
          <li>
            <span class="product-image">
            <a href="<?php echo $subcaturl; ?>">
                     <img src="<?php echo $_category->getImageUrl() ?>" height="180px" width="180px">
            </a>             
            </span>

             <span class="product-item-name">
             <a href="<?php echo $subcaturl ?>" class="product-item-link"><?php echo $subcat->getName(); ?></a>
             </span>
         </li>

 <?php  } ?>
</ul>